"""Add budget tables and settings life data

Revision ID: b3f2ebf73bd2
Revises: c3d4e5f6g7h8
Create Date: 2026-02-09 05:11:13.543578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b3f2ebf73bd2'
down_revision: Union[str, Sequence[str], None] = 'c3d4e5f6g7h8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('bank_transactions', sa.Column('duplicate_confidence', sa.Float(), nullable=True))
    op.add_column('bank_transactions', sa.Column('duplicate_reason', sa.String(), nullable=True))
    op.create_index('idx_bank_transactions_is_duplicate', 'bank_transactions', ['is_duplicate'], unique=False)
    op.create_index('idx_bank_tx_duplicate_lookup', 'bank_transactions', ['user_id', 'date', 'currency'], unique=False)
    op.add_column('settings', sa.Column('marital_status', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('housing_type', sa.String(), nullable=True))
    op.add_column('settings', sa.Column('children_age_range', sa.String(), nullable=True))
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('true'))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'is_first_login',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('true'))
    op.drop_column('settings', 'children_age_range')
    op.drop_column('settings', 'housing_type')
    op.drop_column('settings', 'marital_status')
    op.drop_index('idx_bank_tx_duplicate_lookup', table_name='bank_transactions')
    op.drop_index('idx_bank_transactions_is_duplicate', table_name='bank_transactions')
    op.drop_column('bank_transactions', 'duplicate_reason')
    op.drop_column('bank_transactions', 'duplicate_confidence')
    # ### end Alembic commands ###
