"""Add include_partner_finances to settings

Revision ID: fb6043325432
Revises: b3f2ebf73bd2
Create Date: 2026-02-09 11:45:09.635295

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fb6043325432'
down_revision: Union[str, Sequence[str], None] = 'b3f2ebf73bd2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('settings', sa.Column('include_partner_finances', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('settings', 'include_partner_finances')
    # ### end Alembic commands ###
